#!/bin/bash
# Run tests, waiting for a proper test suite
cargo deps --no-transitive-deps  | dot -Tpng > graph.png

rm ./target/debug/xsesame
cargo build
clear


./target/debug/xsesame --session-dir test/samples
#./target/debug/xsesame help enable


#LANG=el_GR.utf8 ./target/debug/xsesame --session-dir test/samples list
#LANG=el_GR.utf8 ./target/debug/xsesame --session-dir test/samples
#./target/debug/ xsesame --session-dir test/samples enable cinnamon2d
#./target/debug/ xsesame --session-dir test/samples enable cinnamon2d
#./target/debug/xsesame --session-dir test/samples
#./target/debug/xsesame --session-dir test/samples disable cinnamon2d
#./target/debug/xsesame --session-dir test/samples disable cinnamon2d
#./target/debug/xsesame --session-dir test/samples
#./target/debug/xsesame --session-dir test/samples disable cinnamon2d
#./target/debug/xsesame --session-dir test/samples
#./target/debug/xsesame --session-dir test/samples enable cinnamon2d

./target/debug/xsesame --session-dir test/samples disable cinnamon2d
./target/debug/xsesame --session-dir test/samples disable cinnamon
./target/debug/xsesame --session-dir test/samples disable pop
