[package]
name = "xsesame-core"
version = "0.1.0"
authors = ["Giannis Tsagkatakis <jtsagata@gmail.com>"]
edition = "2018"

[dependencies]
freedesktop_entry_parser = "1.1.1"
serde = "1.0.123"
serde_json = "1.0"
regex = "1.4.3"
colored = "2.0.0"
env-lang = "1.0.0"
